# SERIES


# Punto 1
```{r}
#Definimos la función
serie1 <- function(n){
  suma1 <- 0
  for (i in seq(1,n)){
    suma1 <- suma1 + ((-1)^(i))*tanh(i)
  }
  print(suma1)
}
```
```{r}
#Probamos la serie
x1 <- seq(1,100,5)
y1<- sapply(x1,serie1)
```
```{r}
#Graficamos la serie
plot(x1,y1, type = "o")
```
```{r}
#Hallamos el punto minimo y maximo en que oscila la serie ciclica
min(y1)
max(y1)
```


# Punto2
```{r}
#Definimos la función
serie2 <- function(n){
  suma2 <- 0
  for (i in seq(1,n)){
    suma2 <- suma2 + atan(i)^(2)/((i^2)+1)
  }
  print(suma2)
}
```
```{r}+
#Probamos la serie
x2 <- seq(1,100)
y2<- sapply(x2,serie2)
```
```{r}
#Graficamos la serie
plot(x2,y2, type = "o")
```
```{r}
#Hallamos el punto maximo en que converge la serie
max(y2)
```

# Punto 3
```{r}
#Definimos la función factorial
mi.factorial <- function(n){
    result <- n
    i <- n
    while (i>1){
        result <- (i-1)*result
        i = i-1
    }
    return(result)
}

#Definimos funcion de la serie
serie3 <- function(n){
  suma3 <- 0
  for (i in seq(2,n)){
    suma3 <- suma3+log(mi.factorial(i),i)/ (i^3)
  }
  print(suma3)
}

#Probamos la función
x3 <- seq(2,100)
y3<- sapply(x3,serie3)

#Graficamos la serie
plot(x3,y3, type = "o")
```
```{r}
#Hallamos el punto maximo en que converge la serie
max(y3)
```

# Punto4
```{r}
# Definimos la función
serie4<- function(x, n) {
  sum(sapply(0:n, function(i) {
    ((-1)^i / factorial(2*i + 1)) * x^(2*i + 1)
  }))
}

#Ensayamos la funcion
n <- 100
x4 <- seq(-pi, pi, length.out = 100)
y4 <- sapply(x4, function(x) serie4(x, n))
sin_values <- sin(x4)

# Graficar los resultados
plot(x4, sin_values, type = "l", col = "blue", lwd = 6, ylab = "sin(x)", xlab = "x")
lines(x4, y4, col = "red", lwd = 4, lty = 2)
```


# TRATAMIENTO DE ARCHIVOS
```{r}
#Definimos el directorio de la tarea
getwd()
```
```{r}
setwd(dir = "/workspaces/assignment-r-GregRios27/assignment" )
```

```{r}
datos <- read.table("data.csv", header = F, sep = "\t")
head(datos,5)
```
```{r}
#Punto1
sum(datos$V2)
```
```{r}
#Punto2
table(datos$V1)
```
```{r}
#punto3
tapply(datos$V2, datos$V1, sum)
```